### ISSUE TITLE
failed docker-compose up

### ISSUE THREAD

**Issue by salisbury-espinosa** [figment-networks/polkadothub-proxy#79]
```
Successfully tagged polkadothub-proxy_proxy:latest
WARNING: Image for service proxy was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating polkadothub-proxy            ... done
Creating polkadothub-proxy_go-proto_1 ... done
Attaching to polkadothub-proxy_go-proto_1, polkadothub-proxy
polkadothub-proxy | internal/modules/cjs/loader.js:883
polkadothub-proxy |   throw err;
polkadothub-proxy |   ^
polkadothub-proxy | 
polkadothub-proxy | Error: Cannot find module 'express'
polkadothub-proxy | Require stack:
polkadothub-proxy | - /usr/src/app/cluster.js
polkadothub-proxy |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
polkadothub-proxy |     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
polkadothub-proxy |     at Module.require (internal/modules/cjs/loader.js:952:19)
polkadothub-proxy |     at require (internal/modules/cjs/helpers.js:88:18)
polkadothub-proxy |     at Object.<anonymous> (/usr/src/app/cluster.js:8:17)
polkadothub-proxy |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
polkadothub-proxy |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
polkadothub-proxy |     at Module.load (internal/modules/cjs/loader.js:928:32)
polkadothub-proxy |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
polkadothub-proxy |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
polkadothub-proxy |   code: 'MODULE_NOT_FOUND',
polkadothub-proxy |   requireStack: [ '/usr/src/app/cluster.js' ]
polkadothub-proxy | }
polkadothub-proxy_go-proto_1 exited with code 0
polkadothub-proxy exited with code 1
```

**Comment by salisbury-espinosa** [comment]
fixed by:

```
diff --git a/docker-compose.yml b/docker-compose.yml
index 2d33bc0..b18342f 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -16,6 +16,7 @@ services:
       - "50051:50051"
     volumes:
       - ./:/usr/src/app
+      - /usr/src/app/node_modules
     environment:
       - HOST=0.0.0.0
       - PORT=50051
```
